// Please do NOT edit this file directlly
// To synchronize set/update project configs:
// + From terminal, run $ sheetbase config set key=value|...
// + Or, edit configs in sheetbase.json, then run $ sheetbase config update
export const SHEETBASE_CONFIG = {
   "apiKey": "hD5MJjcssfu8soGUMUbDJ2xlw7Gd4dho",
   "databaseId": "1hIStBMraNFhtLohlW_x0y0wfpH-T4m0mEdv1tb92aWA",
   "emailPrefix": "App"
}