// Please do NOT edit this file directlly
// To synchronize set/update project configs:
// + From terminal, run $ sheetbase config set key=value|...
// + Or, edit configs in sheetbase.json, then run $ sheetbase config update
export const SHEETBASE_CONFIG = {
   "backendUrl": "https://script.google.com/macros/s/AKfycbz5sasMt2Nu_3k5ah8TBSrtpNk3j6DdbkXUiDZ8qbaIkdDis_ofODLgEPsEe7JdaEIo/exec",
   "apiKey": "hD5MJjcssfu8soGUMUbDJ2xlw7Gd4dho",
   "databaseId": "1hIStBMraNFhtLohlW_x0y0wfpH-T4m0mEdv1tb92aWA",
   "databaseGids": {
      "categories": "101",
      "tags": "102",
      "pages": "103",
      "posts": "104",
      "products": "107"
   }
}